version: '3'
services:
  nest:
    container_name: nest
    build: .
    ports:
    - ${API_PORT}:${API_PORT}
    volumes:
    - .:/app
    - /app/node_modules
    networks:
      - docker-network
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: database
    image: 'postgres:13-alpine'
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - docker-network
networks:
  docker-network:

